### ISSUE TITLE
Problem with nginx

### ISSUE THREAD

**Issue by sirramin** [sffc/socketio-file-upload#130]
When I run the server locally without Nginx the file saves fine but when I establish a reverse proxy like Nginx in the middle file didn't save.

**Comment by sffc** [comment]
I have used socketio-file-upload with an nginx proxy before.  Please make sure you have it properly configured to support web sockets.  socketio-file-upload only works as well as socket.io will work.

**Comment by sirramin** [comment]
The socket.io itself works fine but file upload not.
I also use Cloudflare as dns and ssl provider, can this cause the problem?

**Comment by sirramin** [comment]
The problem was from PM2 that had caused permission issues !!

**Comment by sffc** [comment]
Glad you found your problem!
