### ISSUE TITLE
Permission error 34 - uploader.dir = " /var/www/vhosts/chattet.de/maiwell.chattet.de/uploads"; 	

### ISSUE THREAD

**Issue by thE-iNviNciblE** [sffc/socketio-file-upload#67]
i've tried chmod 755. chmod 777 user:usergroup www-data:www-data nothing is working, why?

on an other server it's working

0|app      | Error from uploader { file:
0|app      |    { name: 'a.png',
0|app      |      mtime: Sat Sep 02 2017 13:31:44 GMT+0200 (CEST),
0|app      |      encoding: 'octet',
0|app      |      clientDetail: {},
0|app      |      meta: {},
0|app      |      id: 3,
0|app      |      size: 8380,
0|app      |      bytesLoaded: 0,
0|app      |      success: true },
0|app      |   error:
0|app      |    { [Error: ENOENT, open ' /var/www/vhosts/chattet.de/maiwell.chattet.de/uploads/a.png']
0|app      |      errno: 34,
0|app      |      code: 'ENOENT',
0|app      |      path: ' /var/www/vhosts/chattet.de/maiwell.chattet.de/uploads/a.png' },
0|app      |   memo: 'computing file name' }

**Comment by sffc** [comment]
I don't know the details of your server so it's hard to debug this issue.  Make sure that you have the right user running the node process.  `www-data` is often used for Apache but I'd be surprised if that were the correct user on Node.
