### ISSUE TITLE
How to upload a single file manually  ?

### ISSUE THREAD

**Issue by pokend** [sffc/socketio-file-upload#73]
How can I submit(upload) a single file manually like this function ?
`instance.submitFiles(files)` 

Cordially.

**Comment by ryanaltair** [comment]
web sides
```
var connect = io.connect()
var siofu = new SocketIOFileUpload(connect)
let files = $('whereInputLives').prop('files')
siofu.submitFiles(files)
console.log('hope it works')
```

**Comment by MaxLeiter** [comment]
this can be closed, not really an issue.

**Comment by sffc** [comment]
@pokend, if you are still having this issue, can you elaborate on the situation where you have just a single File variable?  Are you sure you can't get a FileList instead?

I am closing this issue for now but I will reopen if you provide more information.
