### ISSUE TITLE
[Solved] Broken

### ISSUE THREAD

**Issue by RandolphMH** [sffc/socketio-file-upload#74]
When I select a file to upload, I get booted from my connection and an error is thrown in my terminal.
![siofuerror](https://user-images.githubusercontent.com/36911165/36771644-b1f57252-1c1f-11e8-8684-77039e935e51.png)

I'm using Node.js, Express, Socket.IO and SocketIO-File-Upload to upload an image/file at the start of a form that uses BodyParser (tried without this part of form as well).

So far, I listen on port 3001 and connect to a socket no problem. When I select a file to upload (not submit, just select), it drops my node app.js connection on the server side and throws an error.

I'm not quite sure what the issue is. At first, I thought it was because I was listening on port 3000 and connecting to MySQL in the same script. I removed the MySQL part and get the exact same error.

Then, I thought it was my form enctype messing with it (because of the ([object Object]) error). Nope, no change.

Before removing the MySQL part of my script, I attempted to connect on the same port as MySQL (3000) and got different errors. The MySQL threw errors and I got NO socket connection. I received what I found to be a CORS error ( 404 "Access-Control-Allow-Headers").

My code is:

app.js (server-side):

```
var express = require('express');
var app = express();
var siofu = require("socketio-file-upload");
var server = app.use(siofu.router).listen(3001, function(err){
    if (err)
        throw err;
    else {
        console.log('Listening: 3001');
    }
});
var io = require('socket.io')(server);

//Static
app.use(express.static('public'));

io.on('connection', function(socket, err){   
    if (err)
    throw err;
 else {
    var uploader = new siofu();
    uploader.dir = "/uploads";
    uploader.listen(socket);
    console.log('Socket: Connected', socket.id);
 }
});
```

index.html (form page):

```
<!DOCTYPE html>
<html>
  <head>

    <meta charset="utf-8">
    <meta name="robots" content="nofollow" />
    <meta name="googlebot" content="nofollow" />

    <meta name="description" content="" />

    <meta name="google" content="nositelinkssearchbox" />

        <title>Form</title>

    <script src="/socket.io/socket.io.js"></script>
    <link rel="stylesheet" href="u.css">

  </head>

  <body>

<form id="data-uplink-form" method="post" enctype="multipart/form-data">

        <input type="file" id="imgup" class="frmtxt wdth mbtf" />

    </form>
    <script src="/siofu/client.js"></script>
    <script src="/formpage.js"></script>
  </body>
</html>
```

This is the .js called at the bottom:

```
//Make connection to server
var socket = io.connect('http://x.x.x.x:3001');
var uploader = new SocketIOFileUpload(socket);
uploader.listenOnInput(document.getElementById("imgup"));
```

I attempted to look into the errors I received when connecting to 3001 and selecting a file. I'm not sure where the calls lead to, though.

What is causing this set of errors?

Is it to do with JSON (regards to the ([object Object]) part of error)?
Am I missing something?
Is my code trash?
Should I go back to playing with Legos?

**Comment by sffc** [comment]
Add an error handler on the server to log what the error is:

```javascript
    uploader.on("error", function(event){
        console.log("Error from uploader", event);
    });
```

I think it might have something to do with file permissions or the uploads directory not existing.

**Comment by RandolphMH** [comment]
@sffc Shane, I appreciate the help! I was wondering how I could get the error. You were correct with your assumption that the uploads directory doesn't exist. 

What gets me is the fact that I made my uploads folder in every possible directory to combat this. There's nowhere left to make a folder.

In which directory will the upload get pushed to?
Straight to root?
root/uploads?
In root/location-of-file-uploader/uploads?
In /var/www/html?
var/www/html/uploads?
In var/www/html/location-of-file-uploader/uploads?

This is the error I received:
![image](https://user-images.githubusercontent.com/36911165/36858671-b91dc162-1d49-11e8-8750-58c72f125cd4.png)

Once again, thank you. Have a great weekend!

**Comment by sffc** [comment]
You have your upload directory set in this line:

```
uploader.dir = "/uploads";
```

That is the directory you need to make with the right permissions, `/uploads`.  If you want a different directory, change that line.

**Comment by RandolphMH** [comment]
I get confused at times with directories. Sometimes, the stated dir gets appended to the end of the dir the file is in. Sometimes, it appends to /root/. Etc, etc.

Directories when working on different ports is a real brain-exploder for me.

Guess I need to binge on how directories work. Thank you boss, I value your time!

**Comment by MaxLeiter** [comment]
this can be closed
