### ISSUE TITLE
acknowledgement for siofu_progress

### ISSUE THREAD

**Issue by kuanysh-nabiyev** [sffc/socketio-file-upload#80]
Hi, thanks for your great work
Is it possible to call acknowledgement callback function for siofu_progress event when processing file chunk is finished?
I know about siofu_chunk event, but I don't want to send unrelated siofu_chunk event to every connected socket.
we use your library for our android, ios apps

**Comment by sffc** [comment]
I don't see wiring for this feature right now, but it would be easy to add.

In client.js, line 210, there is a function processChunk:

```js
var processChunk = function () {
```

In that function, after the `communicator.abort` check, dispatch a new event:

```js
			_dispatch("chunk-acknowledged", {
				file: file,
				bytesLoaded: offset,
				name: newName
			});
```

However, the "progress" event for the next chunk is emitted soon after the proposed "chunk-acknowledged" event.  Why do you need both?  (I don't have a strong opinion, just curious)

**Comment by sffc** [comment]
^ if you want the "chunk-acknowledged" event, send a PR and I will be happy to accept it.

**Comment by kuanysh-nabiyev** [comment]
Thanks for your suggestion, but I mean socket.io acknowledgement callback function.
https://socket.io/docs/client-api/#socket-emit-eventName-%E2%80%A6args-ack
When you emit "siofu_chunk" event, it will be catched by all connected sockets.
For example, there are 2 users who send a file. The "siofu_chunk" event of the first user file will be emitted to the second user, while  the "siofu_chunk" event of the second user file will be emitted to the first user. And imagine if you have 100 users who upload file. Instead of notify only the file sender, the event will be emitted to other 99 users.

I have solved the issue by emitting another event on server side:
uploader.on("progress", event => {
      client.emit(`siofu_chunk:${event.file.id}`);
});
