### ISSUE TITLE
Whitelist allowed extensions?

### ISSUE THREAD

**Issue by mrbluecoat** [sffc/socketio-file-upload#87]
Is there a way to restrict uploads by extension / mime-type?  (e.g. only allow png,jpg,jpeg,gif)

**Comment by sffc** [comment]
Yes.  Here is how you can do this:

https://github.com/sffc/socketio-file-upload#instanceabortid-socket

You can also use the `uploadValidator` function to do your checking.

On the client side, you can do the check in the "choose" event:

https://github.com/sffc/socketio-file-upload#choose

**Comment by mrbluecoat** [comment]
Thanks @sffc!

For anyone needing a bit more elaboration, here's the solution that worked for me:

**index.html**

```
siofu.addEventListener("choose", function(event){
  Array.from(event.files).forEach(file => {
    if (!/^.*\.(jpg|jpeg|gif|png)$/.test(file.name.toLowerCase())) {
      console.error("Invalid file type.");
      return false;
    }
  });
});
```

**app.js**

```
uploader.on("start", event => {
  if (!/^.*\.(jpg|jpeg|gif|png)$/.test(event.file.name.toLowerCase())) {
    uploader.abort(event.file.id, socket);
  }
});
```
